version: '3'

services:

  db:
    image: 'postgres:13.1-alpine'
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=mpluser
      - POSTGRES_PASSWORD=mplpassword
      - POSTGRES_DB=mpl
  app:
    image: 'deedat95/docker-spring-boot-postgres:latest'
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mpl
      - SPRING_DATASOURCE_USERNAME=mpluser
      - SPRING_DATASOURCE_PASSWORD=mplpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8080:8080'